[package]
name = "wpisim"
version = "0.2.0"
authors = ["Patrick Goldinger"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
utils = { path = "../utils" }

[lib]
name = "wpisim"
crate-type = ["cdylib"]
